services:
  fastapi:
    build:
      context: .  # Current directory
      dockerfile: Dockerfile
    container_name: my-rag-container-prod
    ports:
      - "80:80"
    volumes:
      - qdrant_data_prod:/webapp/qdrant_storage  # Named volume for persistence
    environment:
      - ENV=production
    command: ["uvicorn", "webapp.main:app", "--host", "0.0.0.0", "--port", "80"]
    networks:
      - app_network

volumes:
  qdrant_data_prod: # Production-specific data

networks:
  app_network:
    driver: bridge
