name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Load Secrets from .secrets File
      run: |
        if [ -f .github/workflows/.secrets ]; then
          export $(cat .github/workflows/.secrets | xargs)
        else
          echo ".secrets file not found!"
          exit 1
        fi

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image to Docker Hub
      run: |
        docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$TAG .
        docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$TAG

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container App
      run: |
        az containerapp create \
          --name $AZURE_APP_NAME \
          --resource-group $AZURE_RESOURCE_GROUP \
          --image $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$TAG \
          --cpu 0.5 \
          --memory 1.0Gi \
          --ingress external \
          --target-port 80
